"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("./index");
var SchoolObject = new index_1.School();
var AreaObject = new index_1.Area("Computer Science");
var LevelObject = new index_1.Level("Medium", "Programming");
var GroupObject = new index_1.Group("Web Development", "Medium");
var StudentIra = new index_1.Student("Ira", "Ryzha", 2006);
SchoolObject.addArea(AreaObject);
AreaObject.addLevel(LevelObject);
LevelObject.addGroup(GroupObject);
StudentIra.grade = { workName: "Math", mark: 11 };
StudentIra.grade = { workName: "Programming", mark: 12 };
StudentIra.grade = { workName: "English", mark: 10 };
StudentIra.grade = { workName: "Sport", mark: 8 };
StudentIra.grade = { workName: "Other", mark: 16 };
StudentIra.visit = { lesson: "Math", present: true };
console.log(StudentIra);
console.log(StudentIra.getPerformanceRating());
GroupObject.addStudent(StudentIra);
console.log(GroupObject);
